"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['mailtoplus.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': dict(
        CFBundleName='mailtoplus',
        CFBundleShortVersionString='2.0.6',
        CFBundleVersion='2.0.6',
        CFBundleIdentifier='net.adelt.philipp.mailtoplus',
        CFBundleURLTypes=[dict(
            CFBundleURLName='mailtoplus',
            CFBundleURLSchemes=['mailtoplus'],
        )],
    ),
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
